### ISSUE TITLE
vim-nodejs-complete does not work when set omnifunc in advance

### ISSUE THREAD

**Issue by Layzie** [myhere/vim-nodejs-complete#5]
Hi.

I write in my .vimrc below setting for using omni complete.

`autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS`.

Then `vim-nodejs-complete` can't work, so I commented out above setting, then `vim-nodejs-complete` work well.

Is there any idea for work `vim-nodejs-complete` in existence of above setting?

Thanks.

**Comment by myhere** [comment]
Hi.

the `omnifunc` is `nodejscomplete#CompleteJS`, not `javascriptcomplete#CompleteJS`, see [here](https://github.com/myhere/vim-nodejs-complete/blob/master/after/ftplugin/javascript.vim). It's defined in [vim-nodejs-complete/after/autoload/nodejscomplete.vim](https://github.com/myhere/vim-nodejs-complete/blob/master/after/autoload/nodejscomplete.vim)

Thanks for using it.

**Comment by Layzie** [comment]
Thanks for your reply!

So, I can use only `vim-nodejs-complete` when I set no omnifunc for JavaScript in advance, right?

**Comment by myhere** [comment]
No, it's not.

use `vim-nodejs-complete`, you will have both `javascript` and `nodejs`'s completion in one place.

`vim-nodejs-complete` will call `javascriptcomplete#CompleteJS`, so it will complete for `javascript` and `nodejs` .see [here](https://github.com/myhere/vim-nodejs-complete/blob/master/after/autoload/nodejscomplete.vim#L19)

**Comment by Layzie** [comment]
Ok, I understand.

I use [neocomplecache](https://github.com/Shougo/neocomplcache), maybe this plugin's settings doesn't go well in my environment. 

Thanks for your answers!

**Comment by lfilho** [comment]
Hey guys, sorry to comment on this closed issue again but I can't seem to get the plugin working.

I installed it via Vundle (is it a problem?). Then restarted vim, opened the `test/a.js` file and tried: `var foo = req<c-n>` and it only completed to `require` not `require('` as expected. `<c-n>` is the neocomplecache mapping.
Then I tried with `var foo = req<c-x><c-o>` and then it completed to `XMLHttpRequest` (?!).

What am I doing wrong? Thanks!

**Comment by myhere** [comment]
sorry, i forgot to update the readme.

it doesn't support require complete after i rewrite some code

**Comment by lfilho** [comment]
Oh, ok. :)

Nonetheless, I've tried the other examples and they didn't work as well: `process.ex` and then `<c-x><x-o>` or also `<c-n>` returned `Keyword completion (^O^N^P) Pattern not found` and `Keyword completion (^N^P) Pattern not found` respectively.

Any clues?? :frowning:

**Comment by lfilho** [comment]
Bump. @myhere? :)

@Layzie did you get this to work with neocomplcache?

Thanks

**Comment by myhere** [comment]
sorry. @lfilho 

it seems that `<c-x><c-o>` cannot work with neocomplete.

maybe neocomplete will call `c-x_c-o` implicitly.

**Comment by lfilho** [comment]
@Shougo, any thoughts? Thanks

**Comment by Shougo** [comment]
Hi, I will test it later. :-)

**Comment by Shougo** [comment]
I tested it and think it is better in after/ftplugin/javascript.vim

```
if exists('&ofu') || exists('g:nodejs_complete_config')
    setlocal omnifunc=nodejscomplete#CompleteJS
endif
```

**Comment by Shougo** [comment]
I tested it, but member completion is not worked...
variables completion and arguments completion and module name completion work.

**Comment by Shougo** [comment]
It is for neocomplcache settings. But it may heavy.

```
  " For vim-nodejs-complete.
  let g:neocomplcache_omni_functions.javascript =
        \ 'nodejscomplete#CompleteJS'
  let g:nodejs_complete_config = {
        \  'js_compl_fn': 'jscomplete#CompleteJS',
        \  'max_node_compl_len': 15
        \}
  let g:neocomplcache_omni_patterns.javascript = '\h\w*\|[^. \t]\.\w*'
```

**Comment by Layzie** [comment]
@lfilho

> @Layzie did you get this to work with neocomplcache?

I tried before. But complete func was heavy and buggy ;(
So, I gave up.

**Comment by lfilho** [comment]
Thanks so much, everybody, for trying to help. @Shougo you're the best! But it got indeed hard to use.

I decided to give it all up (jscomplete, node js complete...). Each one of these plugins work nice alone, but turns out I don't need "only one" of them. When I edit javascript files, I wanna have node AND regular javascript completion AND necomplcache of course. But they just don't play nice together. I got tired.

Now I'm only using Neocomplcache + a node dictionary + a javascript dictionary.

I will try https://github.com/marijnh/tern_for_vim later to see if it plays nice... :)

If anyone reads this in the future and knows of a better vim + javascript world, let me know :)

Thanks

**Comment by Forethinker** [comment]
@lfilho: 

```
Neocomplcache + a node dictionary + a javascript dictionary.
```

How are you doing this? Just using the code that Shougo posted? I added the following line:

```
        if !exists('g:neocomplcache_omni_functions')
            let g:neocomplcache_omni_functions = {}
        endif
```

but it is still not working for me.

**Comment by lfilho** [comment]
You check it on my dotfiles repo:
Using this node dict: https://github.com/lfilho/dotfiles/blob/master/vim/bundles.vim#L35
This javascript dict: https://github.com/lfilho/dotfiles/tree/master/vim/dict
And then this config: https://github.com/lfilho/dotfiles/blob/master/vim/plugin/settings/neocomplcache.vim#L44-L46

**Comment by mcabrams** [comment]
I've got the same problem as @lfilho. It's a shame, was really looking forward to using this. Same issue with @ahayman's fork of this. I'm using YouCompleteMe, not neocomplache, btw.
